name: ShellCheck
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install GNU make
        run: sudo apt-get update && sudo apt-get -y install make shellcheck

      - uses: actions/checkout@v2

      - name: Run make shellcheck
        run: make shellcheck
